### ISSUE TITLE
Write client in Go

### ISSUE THREAD

**Issue by esote** [majiru/cursedhat#5]

**Comment by b-esc** [comment]
im doing this, i made my own repo so moody doesn't have to edit his git history

**Comment by esote** [comment]
@b-esc Okay. I've already pushed a new branch to this repository with a Go client that can receive messages from the OCaml server. I don't think any editing of git history is needed, just merging pull requests between branches, but I can switch to your repository if needed.

**Comment by esote** [comment]
Closing since we've got a Go client and a text-based user interface in @b-esc's repo.
